name: Deployment

on:
  push:
    tags:
      - 'release-*'
    branches:
      - master

jobs:
  deploy-production:
    if: startsWith(github.ref, 'refs/tags/release')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: deploynicolau
        password: dckr_pat_bOlPue_RenyNjpMSuLGWEu3MKT4

 
    - name: Build and push Docker image for production
      run: |
        docker compose -f docker-compose.yml build
        docker tag mathmlcloud-app:latest deploynicolau/mathml:production
        docker push deploynicolau/mathml:production
    - name: Deploy to production
      if: github.ref == 'refs/heads/release'
      run: |
        echo "Deploying to production environment"
        docker compose -f docker-compose.yml up -d

  deploy-staging:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: deploynicolau
        password: dckr_pat_bOlPue_RenyNjpMSuLGWEu3MKT4
    
    - name: Build and push Docker image for production
      run: |
        docker compose -f docker-compose.yml build
        docker tag mathmlcloud-app:latest deploynicolau/mathml:staging
        docker push deploynicolau/mathml:staging
    - name: Deploy to production
      if: github.ref == 'refs/heads/master'
      run: |
        echo "Deploying to staging environment"
        docker compose -f docker-compose.yml up -d
  
  update-staging:
    needs: deploy-staging
    runs-on: [self-hosted, hml]
    steps:
      - name: Pull image from docker hub
        run: docker pull deploynicolau/mathml:staging
      - name: Delete old container
        run: docker rm -f mathml 
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name mathml deploynicolau/mathml:staging
        
  update-production:
    needs: deploy-production
    runs-on: [self-hosted, prod]
    steps:
      - name: Pull image from docker hub
        run: docker pull deploynicolau/mathml:production
      - name: Delete old container
        run: docker rm -f mathml 
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name mathml deploynicolau/mathml:production